### ISSUE TITLE
No data input 

### ISSUE THREAD

**Issue by roborol** [banny310/hoymiles-dtu-homeassistant-addon#4]
Hi, maybe there is one how can help.
I get no data in from the DTU.
![2023-08-05 09_54_42-Home Assistant – Mozilla Firefox](https://github.com/banny310/hoymiles-dtu-homeassistant-addon/assets/138994213/6e54bbb6-abf5-4adc-b44d-d9d2fcf20379)
![2023-08-05 09_54_00-Home Assistant – Mozilla Firefox](https://github.com/banny310/hoymiles-dtu-homeassistant-addon/assets/138994213/dce4c7a4-4bc6-4db5-a6ba-cce52dc88414)
![2023-08-05 09_53_11-Übersicht – Home Assistant – Mozilla Firefox](https://github.com/banny310/hoymiles-dtu-homeassistant-addon/assets/138994213/518d6edc-9545-423c-998f-166184c196b6)

**Comment by daspi-ds** [comment]
Hello,
I've got exactly the same problem. also get no data.

**Comment by roborol** [comment]
Hello, until now i have no solution for this problem 😪

**Comment by pawlizio** [comment]
Have the same issue. Checking the logs, the add-on receives data but is not able to match them. 

```
INFO  | 2023-10-03 12:29:57 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:97) - dtuSn: "XXXXXXXXXXXX", time: 1696328994, packetCount: 1, ver: 1, sgsDatas {,   sn: XXXXXXXXXXXX,   ver: 1,   v: 2334,   freq: 5004,   p: 1700,   i: 72,   pf: 999,   temp: 232,   wnum: 74,   crc: 8281,   link: 1,   miSignal: 203426828, }, pvDatas {,   sn: XXXXXXXXXXXX,   pi: 1,   v: 303,   i: 144,   p: 438,   et: 230,   ed: 230,   code: YYYYYYYYYY, }, pvDatas {,   sn: XXXXXXXXXXXX,   pi: 2,   v: 293,   i: 154,   p: 453,   et: 232,   ed: 232,   code: YYYYYYYYYY, }, pvDatas {,   sn: XXXXXXXXXXXX,   pi: 3,   v: 294,   i: 152,   p: 449,   et: 231,   ed: 231,   code: YYYYYYYYYY, }, pvDatas {,   sn: XXXXXXXXXXXX,   pi: 4,   v: 293,   i: 152,   p: 448,   et: 235,   ed: 231,   code: YYYYYYYYYY, }, 
INFO  | 2023-10-03 12:29:57 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:101) - <-- end
INFO  | 2023-10-03 12:29:57 | [nioEventLoopGroup-2-1] dtu.SimpleMessageAggregator (SimpleMessageAggregator.java:40) - Next message, last=true
ERROR | 2023-10-03 12:29:57 | [nioEventLoopGroup-2-1] dtu.DtuClient$InboundHandler (DtuClient.java:187) - exceptionCaught: io.netty.handler.codec.MessageAggregationException: Message number mismatch
io.netty.handler.codec.DecoderException: io.netty.handler.codec.MessageAggregationException: Message number mismatch
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[app.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[app.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[app.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[app.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[app.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[app.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[app.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[app.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[app.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[app.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[app.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[app.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[app.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: io.netty.handler.codec.MessageAggregationException: Message number mismatch
	at com.hoymiles.infrastructure.dtu.SimpleMessageAggregator.decode(SimpleMessageAggregator.java:42) ~[app.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[app.jar:?]
	... 25 more
```

**Comment by Chalcear** [comment]
hello , where does you knows the dtu host and port , i have trying many options but i have already  the same message and doesn't connect to the dtu:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:49:23] INFO: /data/options.json exists!
[17:49:27] INFO: MQTT: host=core-mosquitto, port=1883, username=addons, password=hogaemohl6ietho5ree6ino0ohwahg4shohgiMiephee5ook8ahCeuga2menae6m
[17:49:29] INFO: DTU: host=10.10.100.155, port=10081
[17:49:30] INFO: banny310 - Home Assistant Hoymiles DTU Solar Data Gateway Add-on
[17:49:30] INFO: Configuration:
{
  "dtu": {
    "host": "10.10.100.155",
    "port": 10081
  },
  "app": {},
  "app_mode_active": {},
  "app_mode_passive": {},
  "mqtt": {
    "host": "core-mosquitto",
    "port": "1883",
    "username": "addons",
    "password": "hogaem0ohwahgeuga2menae6m"
  }
}
[17:49:30] INFO: Starting...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  | 2023-10-17 17:49:39 | [main] hoymiles.Entrypoint (Entrypoint.java:15) - Starting...
INFO  | 2023-10-17 17:49:39 | [main] hoymiles.Entrypoint (Entrypoint.java:16) - TimeZone: Europe/Paris
INFO  | 2023-10-17 17:49:40 | [main] bootstrap.WeldStartup (WeldStartup.java:148) - WELD-000900: 4.0.3 (Final)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1 (file:/app.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  | 2023-10-17 17:49:42 | [main] bootstrap.WeldStartup (WeldStartup.java:236) - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
