### ISSUE TITLE
Add-on not starting

### ISSUE THREAD

**Issue by hombre-13hb** [banny310/hoymiles-dtu-homeassistant-addon#5]
hi, 
add-on is not starting, can you help ? thx

here is the log :  

  [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:11:53] INFO: /data/options.json exists!
[12:11:54] INFO: MQTT: host=core-mosquitto, port=1883, username=addons, password=xxx
[12:11:55] INFO: DTU: host=192.168.1.88, port=10081
[12:11:56] INFO: banny310 - Home Assistant Hoymiles DTU Solar Data Gateway Add-on
[12:11:56] INFO: Configuration:
{
  "dtu": {
    "host": "192.168.1.88",
    "port": 10081
  },
  "app": {},
  "app_mode_active": {},
  "app_mode_passive": {},
  "mqtt": {
    "host": "core-mosquitto",
    "port": "1883",
    "username": "addons",
    "password": "xxx"
  }
}
[12:11:56] INFO: Starting...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  | 2023-09-11 12:12:00 | [main] hoymiles.Entrypoint (Entrypoint.java:15) - Starting...
INFO  | 2023-09-11 12:12:00 | [main] hoymiles.Entrypoint (Entrypoint.java:16) - TimeZone: Europe/Luxembourg
INFO  | 2023-09-11 12:12:00 | [main] bootstrap.WeldStartup (WeldStartup.java:148) - WELD-000900: 4.0.3 (Final)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1 (file:/app.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  | 2023-09-11 12:12:01 | [main] bootstrap.WeldStartup (WeldStartup.java:236) - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Exception in thread "main" org.jboss.weld.exceptions.WeldException
	at org.jboss.weld.executor.AbstractExecutorServices.checkForExceptions(AbstractExecutorServices.java:82)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:59)
	at org.jboss.weld.executor.AbstractExecutorServices.invokeAllAndCheckForExceptions(AbstractExecutorServices.java:67)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer.addClasses(ConcurrentBeanDeployer.java:52)
	at org.jboss.weld.bootstrap.BeanDeployment.createClasses(BeanDeployment.java:198)
	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:417)
	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:79)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:813)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:176)
	at com.hoymiles.Entrypoint.main(Entrypoint.java:19)
Caused by: java.lang.OutOfMemoryError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.jboss.weld.executor.AbstractExecutorServices.checkForExceptions(AbstractExecutorServices.java:73)
	... 9 more
Caused by: java.lang.OutOfMemoryError: Java heap space
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by hombre-13hb** [comment]
hi, I reviewed the setup but still it keeps crashing, see log :

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:37:18] INFO: /data/options.json exists!
[13:37:19] INFO: MQTT: host=core-mosquitto, port=1883, username=addons, password=aaCei9aecheiGhooShia7Jieku5she9iuGhaewayaikai3SubahteSh6Ouvie7sh
[13:37:20] INFO: DTU: host=192.168.1.100, port=10081
[13:37:20] INFO: banny310 - Home Assistant Hoymiles DTU Solar Data Gateway Add-on
[13:37:20] INFO: Configuration:
{
  "dtu": {
    "host": "192.168.1.100",
    "port": 10081,
    "watchdog_timeout": 300
  },
  "app": {
    "store_messages_in_excel": false,
    "mode": "passive"
  },
  "app_mode_active": {
    "pull_interval": 60
  },
  "app_mode_passive": {
    "set_server_send_time": true,
    "server_send_time": 1
  },
  "mqtt": {
    "host": "core-mosquitto",
    "port": "1883",
    "username": "addons",
    "password": "xxx"
  }
}
[13:37:20] INFO: Starting...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  | 2023-09-26 13:37:25 | [main] hoymiles.Entrypoint (Entrypoint.java:15) - Starting...
INFO  | 2023-09-26 13:37:25 | [main] hoymiles.Entrypoint (Entrypoint.java:16) - TimeZone: Europe/Luxembourg
INFO  | 2023-09-26 13:37:25 | [main] bootstrap.WeldStartup (WeldStartup.java:148) - WELD-000900: 4.0.3 (Final)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1 (file:/app.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  | 2023-09-26 13:37:26 | [main] bootstrap.WeldStartup (WeldStartup.java:236) - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
/run.sh: line 39:   265 Killed                  java -Dconfig.override_with_env_vars=true -Dconfig.file=${APP_CONFIG_PATH} -ea:com.hoymiles -jar ${APP_JAR}
[cmd] /run.sh exited 137
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by Chalcear** [comment]
i have the same issue

**Comment by MariuszSzurgot** [comment]
same issue, so i put note here waiting for solution

**Comment by Chalcear** [comment]
For me the port 10083 on my dtu isn't open.

I have used an other integration 
(dtu has to plug on ethernet not wifi):

https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro

**Comment by elfeo31** [comment]
Same issue, here are the logs:
I don't understand how to setup MQTT, could you help me ?

 [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:59:12] INFO: /data/options.json exists!
[16:59:12] ERROR: Got unexpected response from the API: Service not enabled
[16:59:12] INFO: MQTT: host=, port=, username=, password=
[16:59:12] INFO: DTU: host=192.168.1.253, port=10081
[16:59:12] INFO: banny310 - Home Assistant Hoymiles DTU Solar Data Gateway Add-on
[16:59:12] INFO: Configuration:
{
  "dtu": {
    "host": "192.168.1.253",
    "port": 10081,
    "watchdog_timeout": 600
  },
  "app": {
    "store_messages_in_excel": false,
    "mode": "passive"
  },
  "app_mode_active": {
    "pull_interval": 60
  },
  "app_mode_passive": {
    "set_server_send_time": true,
    "server_send_time": 1
  },
  "mqtt": {
    "host": "",
    "port": "",
    "username": "",
    "password": ""
  }
}
[16:59:12] INFO: Starting...
